# Generated by Django 3.2.4 on 2021-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloog',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bloog',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
