# Generated by Django 3.2.4 on 2021-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210626_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('mydatetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bloog',
        ),
    ]
