# Generated by Django 3.2.4 on 2021-06-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='image',
            field=models.ImageField(upload_to='portapp/images'),
        ),
    ]
