# Generated by Django 3.2.4 on 2021-06-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_alter_port_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='image',
            field=models.ImageField(upload_to='portapp/imagess'),
        ),
    ]
